# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Basic Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  if ENV['PODSOURCE'] == "JENKINS" then
    pod 'BrainCloud', :path => '../braincloud-objc/'
    #pod 'BrainCloudCpp', :path => '../braincloud-objc/braincloud-cpp/'
  elsif ENV['PODSOURCE'] == "HOME" then
    pod 'BrainCloud', :path => '~/git/braincloud-objc/'
  else
    pod 'BrainCloud', '4.14.1'
  end

  # Pods for Basic Example

  target 'Basic ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Basic ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '4.0'
                config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '11.0'
                config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
               end
          end
   end
end

