# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Basic Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BrainCloud', '4.13.0'
  # pod 'BrainCloud', :path => '~/git/braincloud-objc/'

  # Pods for Basic Example

  target 'Basic ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Basic ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
